services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kishan@2001
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - mynet
volumes:
  mssql_data:
    name: mssql_data
networks:
  mynet:
    external: true
